import NotFound from '../assets/NotFound.png'
import Defensive from '../assets/defensives'
import ExoticAsset from '../assets/exotics'
import Offensive from '../assets/offensivs'
import Utility from '../assets/utilities'
import { TalentModel } from '../models/TalentModel'
import { DefensiveType } from '../type/DefensiveType'
import { DescentType } from '../type/DescentType'
import { ExoticType } from '../type/ExoticType'
import { OffensiveType } from '../type/OffensiveType'
import { UtilityType } from '../type/UtilityType'
import I18nUtils from './I18nUtils'

export default class TalentUtils {
    static talent(type: DescentType): TalentModel.ITalentSetModel | undefined {
        const d = I18nUtils.display()

        const pools = [
            {
                type: DescentType.envy,
                display: d.type[DescentType.envy].display,
                exotics: [
                    { icon: ExoticAsset.PlagueOfTheOutcasts, name: d.exotics[ExoticType.PlagueOfTheOutcasts].display, description: d.exotics[ExoticType.PlagueOfTheOutcasts].description },
                    { icon: ExoticAsset.AgonizingBite, name: d.exotics[ExoticType.AgonizingBite].display, description: d.exotics[ExoticType.AgonizingBite].description },
                    { icon: ExoticAsset.IncessantChatter, name: d.exotics[ExoticType.IncessantChatter].display , description: d.exotics[ExoticType.IncessantChatter].description },
                    { icon: ExoticAsset.BulletHell, name: d.exotics[ExoticType.BulletHell].display, description: d.exotics[ExoticType.BulletHell].description },
                    { icon: ExoticAsset.PaymentinKind, name: d.exotics[ExoticType.PaymentinKind].display, description: d.exotics[ExoticType.PaymentinKind].description },
                    { icon: ExoticAsset.LibertyorDeath, name: d.exotics[ExoticType.LibertyorDeath].display, description: d.exotics[ExoticType.LibertyorDeath].description },
                ],
                offensives: [
                    { icon: Offensive.Allegro, name: d.offensives[OffensiveType.Allegro].display, description: d.exotics[ExoticType.PlagueOfTheOutcasts].description },
                    { icon: NotFound, name: d.offensives[OffensiveType.Clitical].display },
                    { icon: NotFound, name: d.offensives[OffensiveType.Precise].display },
                    { icon: NotFound, name: d.offensives[OffensiveType.Surgical].display },
                    { icon: Offensive.Strained, name: d.offensives[OffensiveType.Strained].display, description: d.offensives[OffensiveType.Strained].description },
                    { icon: Offensive.Vigilance, name: d.offensives[OffensiveType.Vigilance].display, description: d.offensives[OffensiveType.Vigilance].description },
                    { icon: Offensive.Unhinged, name: d.offensives[OffensiveType.Unhinged].display, description: d.offensives[OffensiveType.Unhinged].description },
                    { icon: Offensive.Rifleman, name: d.offensives[OffensiveType.Rifleman].display, description: d.offensives[OffensiveType.Rifleman].description },
                    { icon: Offensive.ClosePersonal, name: d.offensives[OffensiveType.ClosePersonal].display, description: d.offensives[OffensiveType.ClosePersonal].description },
                    { icon: Offensive.Obliterate, name: d.offensives[OffensiveType.Obliterate].display, description: d.offensives[OffensiveType.Obliterate].description },
                    { icon: Offensive.Pummel, name: d.offensives[OffensiveType.Pummel].display, description: d.offensives[OffensiveType.Pummel].description },
                    { icon: Offensive.Spark, name: d.offensives[OffensiveType.Spark].display, description: d.offensives[OffensiveType.Spark].description },
                ],
                defensives: [
                    { icon: NotFound, name: d.defensives[DefensiveType.Insulated].display },
                    { icon: Defensive.AdrenalineRush, name: d.defensives[DefensiveType.AdrenalineRush].display },
                    { icon: Defensive.Clutch, name: d.defensives[DefensiveType.Clutch].display },
                    { icon: Defensive.Efficient, name: d.defensives[DefensiveType.Efficient].display },
                    { icon: Defensive.Entrench, name: d.defensives[DefensiveType.Entrench].display },
                    { icon: Defensive.Leadership, name: d.defensives[DefensiveType.Leadership].display },
                    { icon: NotFound, name: d.defensives[DefensiveType.Preservation].display },
                    { icon: Defensive.ProtectedReload, name: d.defensives[DefensiveType.ProtectedReload].display },
                    { icon: Defensive.Protector, name: d.defensives[DefensiveType.Protector].display },
                    { icon: Defensive.Safeguard, name: d.defensives[DefensiveType.Safeguard].display },
                    { icon: Defensive.Vanguard, name: d.defensives[DefensiveType.Vanguard].display },
                ],
                utilities: [
                    { icon: NotFound, name: d.utilites[UtilityType.Empowered].display },
                    { icon: Utility.Extra, name: d.utilites[UtilityType.Extra].display },
                    { icon: Utility.Surge, name: d.utilites[UtilityType.Surge].display },
                    { icon: Utility.Optimized, name: d.utilites[UtilityType.Optimized].display },
                    { icon: Utility.ShockedandAwe, name: d.utilites[UtilityType.ShockedandAwe].display },
                    { icon: Utility.Perpetuation, name: d.utilites[UtilityType.Perpetuation].display },
                    { icon: Utility.Ignited, name: d.utilites[UtilityType.Ignited].display },
                    { icon: Utility.Eyeless, name: d.utilites[UtilityType.Eyeless].display },
                    { icon: Utility.Trauma, name: d.utilites[UtilityType.Trauma].display },
                    { icon: Utility.Sadist, name: d.utilites[UtilityType.Sadist].display },
                    { icon: Utility.LuckyShot, name: d.utilites[UtilityType.LuckyShot].display },
                    { icon: Utility.FastHands, name: d.utilites[UtilityType.FastHands].display },
                ]
            },
            {
                type: DescentType.gluttony,
                exotics: [
                    { icon: ExoticAsset.EmpathicResolve, name: 'Empathic Resolve' },
                    { icon: ExoticAsset.KineticMomentum, name: 'Kinetic Momentum' },
                    { icon: ExoticAsset.DoctorHome, name: 'Doctor Home' },
                    { icon: NotFound, name: 'Busy Little Bee' },
                    { icon: ExoticAsset.AgonizingBite, name: 'Agonizing Bite' },
                    { icon: ExoticAsset.AdaptiveInstincts, name: 'Adaptive Instincts' },
                ],
                offensives: [
                    { icon: Offensive.Allegro, name: 'Allegro' },
                    { icon: NotFound, name: 'Clitical' },
                    { icon: NotFound, name: 'Precise' },
                    { icon: NotFound, name: 'Surgical' },
                    { icon: NotFound, name: 'Breadbasket' },
                    { icon: Offensive.Companion, name: 'Companion' },
                    { icon: Offensive.Concussion, name: 'Concussion' },
                    { icon: Offensive.Overwatch, name: 'Overwatch' },
                    { icon: Offensive.Optimist, name: 'Optimist' },
                    { icon: Offensive.Vigilance, name: 'Vigilance' },
                    { icon: Offensive.Rifleman, name: 'Rifleman' },
                    { icon: Offensive.Composure, name: 'Composure' },
                ],
                defensives: [
                    { icon: NotFound, name: 'Insulated' },
                    { icon: Defensive.AdrenalineRush, name: 'Adrenaline Rush' },
                    { icon: Defensive.Clutch, name: 'Clutch' },
                    { icon: Defensive.Efficient, name: 'Efficient' },
                    { icon: Defensive.Entrench, name: 'Entrench' },
                    { icon: Defensive.Leadership, name: 'Leadership' },
                    { icon: NotFound, name: 'Preservation' },
                    { icon: Defensive.ProtectedReload, name: 'Protected Reload' },
                    { icon: Defensive.Protector, name: 'Protector' },
                    { icon: Defensive.Safeguard, name: 'Safeguard' },
                    { icon: Defensive.Vanguard, name: 'Vanguard' },
                ],
                utilities: [
                    { icon: NotFound, name: 'Capacitive' },
                    { icon: Utility.Optimized, name: 'Optimized' },
                    { icon: Utility.Extra, name: 'Extra' },
                    { icon: NotFound, name: 'Restorative' },
                    { icon: Utility.Surge, name: 'Surge' },
                    { icon: NotFound, name: 'Destructive' },
                    { icon: Utility.ShockedandAwe, name: 'Shocked and Awe' },
                    { icon: Utility.Salvage, name: 'Salvage' },
                    { icon: Utility.Spike, name: 'Spike' },
                    { icon: Utility.Opportunistic, name: 'Opportunistic' },
                ]
            },
            {
                type: DescentType.greed,
                exotics: [
                    { icon: ExoticAsset.AgonizingBite, name: 'Agonizing Bite' },
                    { icon: ExoticAsset.BreatheFree, name: 'Breathe Free' },
                    { icon: ExoticAsset.DoctorHome, name: 'Doctor Home' },
                    { icon: ExoticAsset.GlassCannon, name: 'GlassCannon' },
                    { icon: ExoticAsset.Regicide, name: 'Regicide' },
                    { icon: ExoticAsset.Sandman, name: 'Sandman' },
                ],
                offensives: [
                    { icon: Offensive.Allegro, name: 'Allegro' },
                    { icon: NotFound, name: 'Clitical' },
                    { icon: NotFound, name: 'Precise' },
                    { icon: NotFound, name: 'Surgical' },
                    { icon: Offensive.Concussion, name: 'Concussion' },
                    { icon: NotFound, name: 'Breadbasket' },
                    { icon: Offensive.Optimist, name: 'Optimist' },
                    { icon: Offensive.Vigilance, name: 'Vigilance' },
                    { icon: Offensive.Rifleman, name: 'Rifleman' },
                    { icon: Offensive.Pummel, name: 'Pummel' },
                    { icon: Offensive.ClosePersonal, name: 'Close & Personal' },
                    { icon: Offensive.Intimidate, name: 'Intimidate' },
                ],
                defensives: [
                    { icon: NotFound, name: 'Insulated' },
                    { icon: Defensive.AdrenalineRush, name: 'Adrenaline Rush' },
                    { icon: Defensive.Clutch, name: 'Clutch' },
                    { icon: Defensive.Efficient, name: 'Efficient' },
                    { icon: Defensive.Entrench, name: 'Entrench' },
                    { icon: Defensive.Leadership, name: 'Leadership' },
                    { icon: NotFound, name: 'Preservation' },
                    { icon: Defensive.ProtectedReload, name: 'Protected Reload' },
                    { icon: Defensive.Protector, name: 'Protector' },
                    { icon: Defensive.Safeguard, name: 'Safeguard' },
                    { icon: Defensive.Vanguard, name: 'Vanguard' },
                ],
                utilities: [
                    { icon: NotFound, name: 'Capacitive' },
                    { icon: NotFound, name: 'Destructive' },
                    { icon: NotFound, name: 'Empowered' },
                    { icon: Utility.Extra, name: 'Extra' },
                    { icon: Utility.Optimized, name: 'Optimized' },
                    { icon: NotFound, name: 'Restorative' },
                    { icon: Utility.Surge, name: 'Surge' },
                    { icon: Utility.Spike, name: 'Spike' },
                    { icon: Utility.Opportunistic, name: 'Opportunistic' },
                    { icon: Utility.Salvage, name: 'Salvage' },
                    { icon: Utility.Braced, name: 'Braced' },
                ]
            },
            {
                type: DescentType.sloth,
                exotics: [
                    { icon: ExoticAsset.Capacitance, name: 'Capacitance' },
                    { icon: ExoticAsset.DisruptorRounds, name: 'Disruptor Rounds' },
                    { icon: NotFound, name: 'Busy Little Bee' },
                    { icon: ExoticAsset.KineticMomentum, name: 'Kinetic Momentum' },
                    { icon: ExoticAsset.LibertyorDeath, name: 'Libertyor Death' },
                    { icon: ExoticAsset.IncessantChatter, name: 'Incessant Chatter' },
                ],
                offensives: [
                    { icon: Offensive.Allegro, name: 'Allegro' },
                    { icon: NotFound, name: 'Clitical' },
                    { icon: NotFound, name: 'Precise' },
                    { icon: NotFound, name: 'Surgical' },
                    { icon: Offensive.Companion, name: 'Companion' },
                    { icon: Offensive.Composure, name: 'Composure' },
                    { icon: Offensive.Gunslinger, name: 'Gunslinger' },
                    { icon: Offensive.Overwatch, name: 'Overwatch' },
                    { icon: Offensive.Spark, name: 'Spark' },
                    { icon: Offensive.Intimidate, name: 'Intimidate' },
                    { icon: Offensive.Vigilance, name: 'Vigilance' },
                    { icon: Offensive.Versatile, name: 'Versatile' },
                ],
                defensives: [
                    { icon: NotFound, name: 'Insulated' },
                    { icon: Defensive.AdrenalineRush, name: 'Adrenaline Rush' },
                    { icon: Defensive.Clutch, name: 'Clutch' },
                    { icon: Defensive.Efficient, name: 'Efficient' },
                    { icon: Defensive.Entrench, name: 'Entrench' },
                    { icon: Defensive.Leadership, name: 'Leadership' },
                    { icon: NotFound, name: 'Preservation' },
                    { icon: Defensive.ProtectedReload, name: 'Protected Reload' },
                    { icon: Defensive.Protector, name: 'Protector' },
                    { icon: Defensive.Safeguard, name: 'Safeguard' },
                    { icon: Defensive.Vanguard, name: 'Vanguard' },
                ],
                utilities: [
                    { icon: NotFound, name: 'Capacitive' },
                    { icon: NotFound, name: 'Destructive' },
                    { icon: NotFound, name: 'Empowered' },
                    { icon: Utility.Optimized, name: 'Optimized' },
                    { icon: Utility.Surge, name: 'Surge' },
                    { icon: Utility.Spike, name: 'Spike' },
                    { icon: Utility.Energize, name: 'Energize' },
                    { icon: Utility.TechSupport, name: 'Tech Support' },
                    { icon: Utility.Skilled, name: 'Skilled' },
                    { icon: Utility.InSync, name: 'InSync' },
                ]
            },
            {
                type: DescentType.wrath,
                exotics: [
                    { icon: ExoticAsset.Bloodsucker, name: 'Bloodsucker' },
                    { icon: ExoticAsset.AdaptiveInstincts, name: 'Adaptive Instincts' },
                    { icon: ExoticAsset.BulletHell, name: 'Bullet Hell' },
                    { icon: ExoticAsset.Sandman, name: 'Sandman' },
                    { icon: ExoticAsset.PlagueOfTheOutcasts, name: 'Plague of the Outcasts' },
                    { icon: ExoticAsset.DoctorHome, name: 'Doctor Home' },
                ],
                offensives: [
                    { icon: Offensive.Allegro, name: 'Allegro' },
                    { icon: NotFound, name: 'Clitical' },
                    { icon: NotFound, name: 'Precise' },
                    { icon: NotFound, name: 'Surgical' },
                    { icon: Offensive.Unhinged, name: 'Unhinged' },
                    { icon: Offensive.Strained, name: 'Strained' },
                    { icon: Offensive.Versatile, name: 'Versatile' },
                    { icon: Offensive.Intimidate, name: 'Intimidate' },
                    { icon: Offensive.Pummel, name: 'Pummel' },
                    { icon: Offensive.Overwhelm, name: 'Overwhelm' },
                    { icon: Offensive.Vigilance, name: 'Vigilance' },
                    { icon: Offensive.Strained, name: 'Strained' },
                ],
                defensives: [
                    { icon: NotFound, name: 'Insulated' },
                    { icon: Defensive.AdrenalineRush, name: 'Adrenaline Rush' },
                    { icon: Defensive.Clutch, name: 'Clutch' },
                    { icon: Defensive.Efficient, name: 'Efficient' },
                    { icon: Defensive.Entrench, name: 'Entrench' },
                    { icon: Defensive.Leadership, name: 'Leadership' },
                    { icon: NotFound, name: 'Preservation' },
                    { icon: Defensive.ProtectedReload, name: 'Protected Reload' },
                    { icon: Defensive.Protector, name: 'Protector' },
                    { icon: Defensive.Safeguard, name: 'Safeguard' },
                    { icon: Defensive.Vanguard, name: 'Vanguard' },
                ],
                utilities: [
                    { icon: NotFound, name: 'Capacitive' },
                    { icon: NotFound, name: 'Destructive' },
                    { icon: Utility.Extra, name: 'Extra' },
                    { icon: Utility.Optimized, name: 'Optimized' },
                    { icon: Utility.LuckyShot, name: 'Lucky Shot' },
                    { icon: Utility.SteadyHands, name: 'Steady Hands' },
                    { icon: Utility.Braced, name: 'Braced' },
                    { icon: Utility.MadBomber, name: 'Mad Bomber' },
                    { icon: Utility.Eyeless, name: 'Eyeless' },
                    { icon: Utility.Vindictive, name: 'Vindictive' },
                    { icon: Utility.Trauma, name: 'Trauma' },
                    { icon: Utility.Salvage, name: 'Salvage' },
                ]
            },
        ]

        return pools.find(p => p.type === type)
    }
}